### ISSUE TITLE
Restrict formatting allowed and accepted from editor

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#217] opened 2022-06-23 14:55 UTC
Because the admin editor (TinyMCE) currently allows anything, including copy and pasting styles, and the frontend presents this with `dangerouslySetInnerHTML` there was some desire to better restrict the tags and content that can be used both by the editor and displayed. 

This could either be done in the backend when the content is delivered to the API or possibly in React. We have to determine what things we want to whitelist, like links, and possibly simple formatting like bold/italic/colors, and block everything else.

**Comment by ssciolla** [comment] 2022-08-03 20:27
This is conceptually a duplicate of #203. I'm going to add this comment to the issue, but close this one to consolidate.

**Closed by ssciolla** 2022-08-03 20:27 UTC
Labels: duplicate, priority: nice to have, task: admin view/tasks, task: instructor view/tasks
